name: SolaSpawn
main: Matthoto\SolaSpawn\Main;
version: 0.0.1
api: 3.0.0
author: Matthoto

commands:
  spawn:
    description: Permet de se tp au spawn
    permission: solaperm.default
    usage: /spawn